-- Hanok Ops standalone backend
-- Project: lludyxgivnmmkovhhrgg (Sydney)

create extension if not exists pg_cron;

create schema if not exists ops_private;
revoke all on schema ops_private from public, anon;
grant usage on schema ops_private to authenticated;

create table public.ops_stores (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint ops_stores_code_format check (code ~ '^[A-Z0-9]{2,8}$')
);

create table public.ops_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text not null default 'User',
  role text not null default 'pending' check (role in ('admin','hq','store','pending')),
  store_id uuid references public.ops_stores(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ops_profiles_store_role_check check (role <> 'store' or store_id is not null)
);

create or replace function ops_private.current_role()
returns text language sql stable security definer set search_path=''
as $$ select p.role from public.ops_profiles p where p.user_id=(select auth.uid()) limit 1 $$;

create or replace function ops_private.current_store_id()
returns uuid language sql stable security definer set search_path=''
as $$ select p.store_id from public.ops_profiles p where p.user_id=(select auth.uid()) limit 1 $$;

revoke all on function ops_private.current_role() from public,anon;
revoke all on function ops_private.current_store_id() from public,anon;
grant execute on function ops_private.current_role() to authenticated;
grant execute on function ops_private.current_store_id() to authenticated;

create table public.ops_tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_no bigint generated by default as identity unique,
  store_id uuid not null references public.ops_stores(id) on delete restrict,
  created_by uuid not null references public.ops_profiles(user_id) on delete restrict,
  assigned_to uuid references public.ops_profiles(user_id) on delete set null,
  title text not null,
  description text not null default '',
  reported_by text,
  category text not null default 'Other' check (category in (
    'Maintenance','Supplier / Stock','IT / POS','Marketing','HR / Staff',
    'Finance','Landlord / Centre','Health & Safety','Other'
  )),
  priority text not null default 'normal' check (priority in ('normal','urgent')),
  status text not null default 'new' check (status in ('new','accepted','in_progress','waiting','completed')),
  due_at timestamptz,
  follow_up_at timestamptz,
  waiting_reason text,
  resolution text,
  accepted_at timestamptz,
  completed_at timestamptz,
  completed_by uuid references public.ops_profiles(user_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ops_tickets_reported_by_length check (reported_by is null or char_length(trim(reported_by)) between 1 and 100),
  constraint ops_tickets_waiting_requires_followup check (
    status <> 'waiting' or (follow_up_at is not null and waiting_reason is not null and length(trim(waiting_reason)) > 0)
  ),
  constraint ops_tickets_completed_requires_resolution check (
    status <> 'completed' or (resolution is not null and length(trim(resolution)) > 0)
  )
);

create table public.ops_ticket_comments (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.ops_tickets(id) on delete cascade,
  author_id uuid not null references public.ops_profiles(user_id) on delete restrict,
  body text not null check (length(trim(body)) > 0),
  created_at timestamptz not null default now()
);

create table public.ops_ticket_attachments (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.ops_tickets(id) on delete cascade,
  uploaded_by uuid not null references public.ops_profiles(user_id) on delete restrict,
  storage_path text not null unique,
  file_name text not null,
  mime_type text,
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  created_at timestamptz not null default now()
);

create table public.ops_ticket_events (
  id bigint generated by default as identity primary key,
  ticket_id uuid not null references public.ops_tickets(id) on delete cascade,
  actor_id uuid references public.ops_profiles(user_id) on delete set null,
  event_type text not null,
  message text not null default '',
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.ops_push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.ops_profiles(user_id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth_key text not null,
  device_label text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, endpoint)
);

create table public.ops_notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_id uuid not null references public.ops_profiles(user_id) on delete cascade,
  ticket_id uuid references public.ops_tickets(id) on delete cascade,
  kind text not null check (kind in ('new_ticket','urgent_unaccepted','normal_unaccepted','due_soon','overdue','follow_up_due','reopen_requested')),
  title text not null,
  body text not null default '',
  priority text not null default 'normal' check (priority in ('normal','urgent')),
  dedupe_key text not null unique,
  data jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.ops_reopen_requests (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.ops_tickets(id) on delete cascade,
  store_id uuid not null references public.ops_stores(id) on delete restrict,
  requested_by uuid not null references public.ops_profiles(user_id) on delete restrict,
  reason text not null check (char_length(trim(reason)) between 3 and 1000),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  reviewed_by uuid references public.ops_profiles(user_id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create index ops_profiles_store_id_idx on public.ops_profiles(store_id);
create index ops_tickets_store_status_idx on public.ops_tickets(store_id,status);
create index ops_tickets_priority_status_idx on public.ops_tickets(priority,status);
create index ops_tickets_assigned_status_idx on public.ops_tickets(assigned_to,status);
create index ops_tickets_due_idx on public.ops_tickets(due_at) where status <> 'completed';
create index ops_tickets_followup_idx on public.ops_tickets(follow_up_at) where status='waiting';
create index ops_tickets_completed_by_idx on public.ops_tickets(completed_by);
create index ops_tickets_created_by_idx on public.ops_tickets(created_by);
create index ops_comments_ticket_created_idx on public.ops_ticket_comments(ticket_id,created_at);
create index ops_ticket_comments_author_id_idx on public.ops_ticket_comments(author_id);
create index ops_attachments_ticket_created_idx on public.ops_ticket_attachments(ticket_id,created_at);
create index ops_ticket_attachments_uploaded_by_idx on public.ops_ticket_attachments(uploaded_by);
create index ops_events_ticket_created_idx on public.ops_ticket_events(ticket_id,created_at);
create index ops_ticket_events_actor_id_idx on public.ops_ticket_events(actor_id);
create index ops_push_user_idx on public.ops_push_subscriptions(user_id);
create index ops_notifications_recipient_created_idx on public.ops_notifications(recipient_id,created_at desc);
create index ops_notifications_recipient_unread_idx on public.ops_notifications(recipient_id,created_at desc) where read_at is null;
create index ops_notifications_ticket_idx on public.ops_notifications(ticket_id);
create unique index ops_reopen_one_pending_per_ticket_idx on public.ops_reopen_requests(ticket_id) where status='pending';
create index ops_reopen_store_created_idx on public.ops_reopen_requests(store_id,created_at desc);
create index ops_reopen_requested_by_idx on public.ops_reopen_requests(requested_by);
create index ops_reopen_reviewed_by_idx on public.ops_reopen_requests(reviewed_by);

create or replace function ops_private.touch_updated_at()
returns trigger language plpgsql security invoker set search_path=''
as $$ begin new.updated_at:=now(); return new; end $$;

create or replace function ops_private.normalize_ticket_state()
returns trigger language plpgsql security invoker set search_path=''
as $$
begin
  new.updated_at:=now();
  if new.status='accepted' and old.status is distinct from 'accepted' then new.accepted_at:=coalesce(new.accepted_at,now()); end if;
  if new.status='completed' and old.status is distinct from 'completed' then
    new.completed_at:=coalesce(new.completed_at,now());
    new.completed_by:=coalesce(new.completed_by,(select auth.uid()));
  elsif old.status='completed' and new.status<>'completed' then
    new.completed_at:=null; new.completed_by:=null;
  end if;
  if new.status<>'waiting' then new.waiting_reason:=null; new.follow_up_at:=null; end if;
  return new;
end $$;

create or replace function ops_private.log_ticket_insert()
returns trigger language plpgsql security definer set search_path=''
as $$ begin
  insert into public.ops_ticket_events(ticket_id,actor_id,event_type,message)
  values(new.id,new.created_by,'created','Ticket created');
  return new;
end $$;

create or replace function ops_private.log_ticket_change()
returns trigger language plpgsql security definer set search_path=''
as $$
begin
  if old.status is distinct from new.status then
    insert into public.ops_ticket_events(ticket_id,actor_id,event_type,message,details)
    values(new.id,(select auth.uid()),'status_changed','Status changed from '||old.status||' to '||new.status,jsonb_build_object('from',old.status,'to',new.status));
  end if;
  if old.assigned_to is distinct from new.assigned_to then
    insert into public.ops_ticket_events(ticket_id,actor_id,event_type,message,details)
    values(new.id,(select auth.uid()),'assignment_changed','Ticket assignment changed',jsonb_build_object('from',old.assigned_to,'to',new.assigned_to));
  end if;
  return new;
end $$;

create or replace function ops_private.handle_new_user()
returns trigger language plpgsql security definer set search_path=''
as $$
begin
  insert into public.ops_profiles(user_id,email,display_name,role,store_id)
  values(new.id,new.email,coalesce(nullif(new.raw_user_meta_data->>'display_name',''),split_part(coalesce(new.email,'user'),'@',1)),'pending',null)
  on conflict(user_id) do nothing;
  return new;
end $$;

create or replace function ops_private.queue_ticket_created_notification()
returns trigger language plpgsql security definer set search_path=''
as $$
begin
  insert into public.ops_notifications(recipient_id,ticket_id,kind,title,body,priority,dedupe_key,data)
  select p.user_id,new.id,'new_ticket',
    case when new.priority='urgent' then 'Urgent new ticket' else 'New store ticket' end,
    s.name||' - '||new.title,
    case when new.priority='urgent' then 'urgent' else 'normal' end,
    'new_ticket:'||new.id::text||':'||p.user_id::text,
    jsonb_build_object('store_id',new.store_id,'ticket_no',new.ticket_no)
  from public.ops_profiles p join public.ops_stores s on s.id=new.store_id
  where p.role in ('admin','hq')
  on conflict(dedupe_key) do nothing;
  return new;
end $$;

create or replace function ops_private.queue_reopen_notification()
returns trigger language plpgsql security definer set search_path=''
as $$
begin
  insert into public.ops_ticket_events(ticket_id,actor_id,event_type,message,details)
  values(new.ticket_id,new.requested_by,'reopen_requested','Store requested ticket to be reopened',jsonb_build_object('request_id',new.id,'reason',new.reason));
  insert into public.ops_notifications(recipient_id,ticket_id,kind,title,body,priority,dedupe_key,data)
  select p.user_id,new.ticket_id,'reopen_requested','Store requested reopen',s.name||' - '||t.title,'normal',
    'reopen_requested:'||new.id::text||':'||p.user_id::text,
    jsonb_build_object('request_id',new.id,'reason',new.reason)
  from public.ops_profiles p join public.ops_tickets t on t.id=new.ticket_id join public.ops_stores s on s.id=new.store_id
  where p.role in ('admin','hq')
  on conflict(dedupe_key) do nothing;
  return new;
end $$;

revoke all on function ops_private.log_ticket_insert() from public,anon,authenticated;
revoke all on function ops_private.log_ticket_change() from public,anon,authenticated;
revoke all on function ops_private.handle_new_user() from public,anon,authenticated;
revoke all on function ops_private.queue_ticket_created_notification() from public,anon,authenticated;
revoke all on function ops_private.queue_reopen_notification() from public,anon,authenticated;

create trigger ops_profiles_touch_updated_at before update on public.ops_profiles for each row execute function ops_private.touch_updated_at();
create trigger ops_push_touch_updated_at before update on public.ops_push_subscriptions for each row execute function ops_private.touch_updated_at();
create trigger ops_tickets_normalize_state before update on public.ops_tickets for each row execute function ops_private.normalize_ticket_state();
create trigger ops_tickets_log_insert after insert on public.ops_tickets for each row execute function ops_private.log_ticket_insert();
create trigger ops_tickets_log_change after update on public.ops_tickets for each row execute function ops_private.log_ticket_change();
create trigger ops_auth_user_created after insert on auth.users for each row execute function ops_private.handle_new_user();
create trigger ops_tickets_queue_notification after insert on public.ops_tickets for each row execute function ops_private.queue_ticket_created_notification();
create trigger ops_reopen_queue_notification after insert on public.ops_reopen_requests for each row execute function ops_private.queue_reopen_notification();

insert into public.ops_stores(code,name) values
('HWD','Hanok Woden'),('HWG','Hanok Wagga'),('PDL','Pandan Leaf'),('MTH','Meathouse'),('BTD','BBQTOWN Dickson');

alter table public.ops_stores enable row level security;
alter table public.ops_profiles enable row level security;
alter table public.ops_tickets enable row level security;
alter table public.ops_ticket_comments enable row level security;
alter table public.ops_ticket_attachments enable row level security;
alter table public.ops_ticket_events enable row level security;
alter table public.ops_push_subscriptions enable row level security;
alter table public.ops_notifications enable row level security;
alter table public.ops_reopen_requests enable row level security;

create policy ops_stores_select on public.ops_stores for select to authenticated using (ops_private.current_role() in ('admin','hq') or id=ops_private.current_store_id());
create policy ops_profiles_select on public.ops_profiles for select to authenticated using (user_id=(select auth.uid()) or ops_private.current_role() in ('admin','hq'));
create policy ops_tickets_select on public.ops_tickets for select to authenticated using (ops_private.current_role() in ('admin','hq') or store_id=ops_private.current_store_id());
create policy ops_tickets_insert on public.ops_tickets for insert to authenticated with check (created_by=(select auth.uid()) and (ops_private.current_role() in ('admin','hq') or store_id=ops_private.current_store_id()));
create policy ops_tickets_update_hq on public.ops_tickets for update to authenticated using (ops_private.current_role() in ('admin','hq')) with check (ops_private.current_role() in ('admin','hq'));
create policy ops_comments_select on public.ops_ticket_comments for select to authenticated using (exists(select 1 from public.ops_tickets t where t.id=ticket_id));
create policy ops_comments_insert on public.ops_ticket_comments for insert to authenticated with check (author_id=(select auth.uid()) and exists(select 1 from public.ops_tickets t where t.id=ticket_id));
create policy ops_attachments_select on public.ops_ticket_attachments for select to authenticated using (exists(select 1 from public.ops_tickets t where t.id=ticket_id));
create policy ops_attachments_insert on public.ops_ticket_attachments for insert to authenticated with check (uploaded_by=(select auth.uid()) and exists(select 1 from public.ops_tickets t where t.id=ticket_id));
create policy ops_events_select on public.ops_ticket_events for select to authenticated using (exists(select 1 from public.ops_tickets t where t.id=ticket_id));
create policy ops_push_select on public.ops_push_subscriptions for select to authenticated using (user_id=(select auth.uid()));
create policy ops_push_insert on public.ops_push_subscriptions for insert to authenticated with check (user_id=(select auth.uid()));
create policy ops_push_update on public.ops_push_subscriptions for update to authenticated using (user_id=(select auth.uid())) with check (user_id=(select auth.uid()));
create policy ops_push_delete on public.ops_push_subscriptions for delete to authenticated using (user_id=(select auth.uid()));
create policy ops_notifications_select_own on public.ops_notifications for select to authenticated using (recipient_id=(select auth.uid()));
create policy ops_notifications_update_own on public.ops_notifications for update to authenticated using (recipient_id=(select auth.uid())) with check (recipient_id=(select auth.uid()));
create policy ops_reopen_select on public.ops_reopen_requests for select to authenticated using (ops_private.current_role() in ('admin','hq') or store_id=ops_private.current_store_id());
create policy ops_reopen_insert_store on public.ops_reopen_requests for insert to authenticated with check (
  requested_by=(select auth.uid()) and store_id=ops_private.current_store_id()
  and exists(select 1 from public.ops_tickets t where t.id=ticket_id and t.store_id=ops_private.current_store_id() and t.status='completed')
);

revoke all on table public.ops_stores,public.ops_profiles,public.ops_tickets,public.ops_ticket_comments,public.ops_ticket_attachments,public.ops_ticket_events,public.ops_push_subscriptions,public.ops_notifications,public.ops_reopen_requests from anon;
grant select on public.ops_stores to authenticated;
grant select on public.ops_profiles to authenticated;
grant update(display_name) on public.ops_profiles to authenticated;
grant select,insert,update on public.ops_tickets to authenticated;
grant select,insert on public.ops_ticket_comments to authenticated;
grant select,insert on public.ops_ticket_attachments to authenticated;
grant select on public.ops_ticket_events to authenticated;
grant select,insert,update,delete on public.ops_push_subscriptions to authenticated;
grant select on public.ops_notifications to authenticated;
grant update(read_at) on public.ops_notifications to authenticated;
grant select,insert on public.ops_reopen_requests to authenticated;
grant usage,select on sequence public.ops_tickets_ticket_no_seq to authenticated;
grant usage,select on sequence public.ops_ticket_events_id_seq to authenticated;

create or replace function public.ops_review_reopen_request(p_request_id uuid,p_approve boolean)
returns void language plpgsql security definer set search_path=''
as $$
declare v_role text; v_req public.ops_reopen_requests%rowtype;
begin
  select p.role into v_role from public.ops_profiles p where p.user_id=(select auth.uid());
  if v_role not in ('admin','hq') then raise exception 'Admin or HQ role required'; end if;
  select * into v_req from public.ops_reopen_requests where id=p_request_id for update;
  if not found then raise exception 'Reopen request not found'; end if;
  if v_req.status<>'pending' then raise exception 'Reopen request already reviewed'; end if;
  update public.ops_reopen_requests set status=case when p_approve then 'approved' else 'rejected' end,reviewed_by=(select auth.uid()),reviewed_at=now() where id=p_request_id;
  if p_approve then
    update public.ops_tickets set status='in_progress' where id=v_req.ticket_id;
    insert into public.ops_ticket_events(ticket_id,actor_id,event_type,message,details)
    values(v_req.ticket_id,(select auth.uid()),'reopened','Ticket reopened after store request',jsonb_build_object('request_id',p_request_id));
  else
    insert into public.ops_ticket_events(ticket_id,actor_id,event_type,message,details)
    values(v_req.ticket_id,(select auth.uid()),'reopen_rejected','Store reopen request rejected',jsonb_build_object('request_id',p_request_id));
  end if;
end $$;

revoke all on function public.ops_review_reopen_request(uuid,boolean) from public,anon;
grant execute on function public.ops_review_reopen_request(uuid,boolean) to authenticated;

create or replace function ops_private.generate_reminders()
returns void language plpgsql security definer set search_path=''
as $$
begin
  insert into public.ops_notifications(recipient_id,ticket_id,kind,title,body,priority,dedupe_key,data)
  select p.user_id,t.id,'urgent_unaccepted','Urgent ticket still unaccepted',s.name||' - '||t.title,'urgent',
    'urgent_unaccepted:'||t.id::text||':'||p.user_id::text||':'||floor(extract(epoch from (now()-(t.created_at+interval '1 hour')))/10800)::bigint::text,
    jsonb_build_object('store_id',t.store_id,'ticket_no',t.ticket_no)
  from public.ops_tickets t join public.ops_stores s on s.id=t.store_id cross join public.ops_profiles p
  where p.role in ('admin','hq') and t.priority='urgent' and t.status='new' and now()>=t.created_at+interval '1 hour'
  on conflict(dedupe_key) do nothing;

  insert into public.ops_notifications(recipient_id,ticket_id,kind,title,body,priority,dedupe_key,data)
  select p.user_id,t.id,'normal_unaccepted','Ticket still unaccepted',s.name||' - '||t.title,'normal',
    'normal_unaccepted:'||t.id::text||':'||p.user_id::text||':'||floor(extract(epoch from (now()-(t.created_at+interval '24 hours')))/86400)::bigint::text,
    jsonb_build_object('store_id',t.store_id,'ticket_no',t.ticket_no)
  from public.ops_tickets t join public.ops_stores s on s.id=t.store_id cross join public.ops_profiles p
  where p.role in ('admin','hq') and t.priority='normal' and t.status='new' and now()>=t.created_at+interval '24 hours'
  on conflict(dedupe_key) do nothing;

  insert into public.ops_notifications(recipient_id,ticket_id,kind,title,body,priority,dedupe_key,data)
  select p.user_id,t.id,'due_soon','Ticket due soon',s.name||' - '||t.title,'normal',
    'due_soon:'||t.id::text||':'||p.user_id::text,jsonb_build_object('due_at',t.due_at,'store_id',t.store_id)
  from public.ops_tickets t join public.ops_stores s on s.id=t.store_id cross join public.ops_profiles p
  where p.role in ('admin','hq') and t.status<>'completed' and t.due_at is not null and t.due_at>now() and t.due_at<=now()+interval '24 hours'
  on conflict(dedupe_key) do nothing;

  insert into public.ops_notifications(recipient_id,ticket_id,kind,title,body,priority,dedupe_key,data)
  select p.user_id,t.id,'overdue','Ticket overdue',s.name||' - '||t.title,case when t.priority='urgent' then 'urgent' else 'normal' end,
    'overdue:'||t.id::text||':'||p.user_id::text||':'||((now() at time zone 'Australia/Sydney')::date)::text,
    jsonb_build_object('due_at',t.due_at,'store_id',t.store_id)
  from public.ops_tickets t join public.ops_stores s on s.id=t.store_id cross join public.ops_profiles p
  where p.role in ('admin','hq') and t.status<>'completed' and t.due_at is not null and t.due_at<now()
  on conflict(dedupe_key) do nothing;

  insert into public.ops_notifications(recipient_id,ticket_id,kind,title,body,priority,dedupe_key,data)
  select p.user_id,t.id,'follow_up_due','Waiting follow-up due',s.name||' - '||t.title,'normal',
    'follow_up_due:'||t.id::text||':'||p.user_id::text||':'||floor(extract(epoch from (now()-t.follow_up_at))/10800)::bigint::text,
    jsonb_build_object('follow_up_at',t.follow_up_at,'waiting_reason',t.waiting_reason,'store_id',t.store_id)
  from public.ops_tickets t join public.ops_stores s on s.id=t.store_id cross join public.ops_profiles p
  where p.role in ('admin','hq') and t.status='waiting' and t.follow_up_at is not null and t.follow_up_at<=now()
  on conflict(dedupe_key) do nothing;
end $$;

revoke all on function ops_private.generate_reminders() from public,anon,authenticated;

insert into storage.buckets(id,name,public,file_size_limit) values('ops-ticket-attachments','ops-ticket-attachments',false,52428800);

create policy ops_storage_read on storage.objects for select to authenticated using (
  bucket_id='ops-ticket-attachments' and exists(select 1 from public.ops_tickets t where t.id::text=(storage.foldername(name))[1])
);
create policy ops_storage_insert on storage.objects for insert to authenticated with check (
  bucket_id='ops-ticket-attachments' and exists(select 1 from public.ops_tickets t where t.id::text=(storage.foldername(name))[1])
);
create policy ops_storage_update on storage.objects for update to authenticated using (
  bucket_id='ops-ticket-attachments' and exists(select 1 from public.ops_tickets t where t.id::text=(storage.foldername(name))[1])
) with check (
  bucket_id='ops-ticket-attachments' and exists(select 1 from public.ops_tickets t where t.id::text=(storage.foldername(name))[1])
);
create policy ops_storage_delete on storage.objects for delete to authenticated using (
  bucket_id='ops-ticket-attachments' and ops_private.current_role() in ('admin','hq')
  and exists(select 1 from public.ops_tickets t where t.id::text=(storage.foldername(name))[1])
);

select cron.schedule('hanok_ops_generate_reminders','*/15 * * * *','select ops_private.generate_reminders();');
